version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=artorimo.settings
    expose:
      - 8000
    volumes:
      - ./assets:/static
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker/letsencrypt-docker-nginx/src/production/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/ohcheestudio.com/fullchain.pem:/etc/letsencrypt/live/ohcheestudio.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/ohcheestudio.com/privkey.pem:/etc/letsencrypt/live/ohcheestudio.com/privkey.pem
      - ./assets:/static
      - /docker-volumes/data/letsencrypt:/data/letsencrypt
      - /var/www/html/blog:/usr/share/nginx/html/blog
    depends_on:
      - server
  redis:
    image: redis:3.2
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
